import type { Block } from '@/types'
import { generateId } from './utils'

export interface DocTemplate {
  id: string
  name: string
  icon: string
  description: string
  buildDoc: () => Block[]
}

export const DOC_TEMPLATES: DocTemplate[] = [
  {
    id: 'blank',
    name: '空白ドキュメント',
    icon: 'file',
    description: '白紙から始める',
    buildDoc: () => [{ id: generateId(), type: 'paragraph', content: '' }],
  },
  {
    id: 'business-letter',
    name: 'ビジネスレター',
    icon: 'mail',
    description: 'ビジネス文書・送付状',
    buildDoc: () => [
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '差出人名\n所属・部署\n住所\n電話番号\nメールアドレス' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '宛先名 様\n所属・部署\n住所' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '拝啓　時下ますますご清祥のこととお慶び申し上げます。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '本文をここに入力してください。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '何卒よろしくお願い申し上げます。' },
      { id: generateId(), type: 'paragraph', content: '敬具' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '署名\n役職\n氏名', align: 'right' },
    ],
  },
  {
    id: 'meeting',
    name: '議事録',
    icon: 'notebookPen',
    description: '会議の記録・決定事項',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '会議議事録' },
      { id: generateId(), type: 'paragraph', content: '日時: 20XX年XX月XX日 XX:XX〜XX:XX' },
      { id: generateId(), type: 'paragraph', content: '参加者: ' },
      { id: generateId(), type: 'h2', content: '議題1' },
      { id: generateId(), type: 'bullet', content: '議論内容を記載' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '議題2' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: 'アクションアイテム' },
      { id: generateId(), type: 'checklist', content: '担当者: タスク内容（期限: XX月XX日）', checked: false },
      { id: generateId(), type: 'checklist', content: '', checked: false },
      { id: generateId(), type: 'h2', content: '次回予定' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'proposal',
    name: 'プロジェクト企画書',
    icon: 'clipboardList',
    description: '企画・提案の構成テンプレート',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: 'プロジェクト企画書' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: '概要' },
      { id: generateId(), type: 'paragraph', content: 'プロジェクトの全体像を簡潔に記載します。' },
      { id: generateId(), type: 'h2', content: '背景' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '目的' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'スコープ' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'タイムライン' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '予算' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'report',
    name: 'レポート',
    icon: 'barChart',
    description: '学術・業務レポート',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: 'レポートタイトル' },
      { id: generateId(), type: 'h2', content: '要旨' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'はじめに' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '方法' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '結果' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '結論' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'resume',
    name: '履歴書',
    icon: 'user',
    description: '職務経歴・自己紹介',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '履歴書' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'h2', content: '基本情報' },
      { id: generateId(), type: 'paragraph', content: '氏名: ' },
      { id: generateId(), type: 'paragraph', content: '生年月日: ' },
      { id: generateId(), type: 'paragraph', content: '住所: ' },
      { id: generateId(), type: 'paragraph', content: '連絡先: ' },
      { id: generateId(), type: 'h2', content: '学歴' },
      { id: generateId(), type: 'paragraph', content: '20XX年X月　〇〇大学 〇〇学部 卒業' },
      { id: generateId(), type: 'h2', content: '職歴' },
      { id: generateId(), type: 'paragraph', content: '20XX年X月　株式会社〇〇 入社' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '資格・スキル' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '自己PR' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'weekly-report',
    name: '週次報告書',
    icon: 'calendar',
    description: '週の業務報告・進捗管理',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '週次報告書' },
      { id: generateId(), type: 'paragraph', content: '報告者: 　　　　報告日: 20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '対象期間: XX月XX日〜XX月XX日' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'h2', content: '今週の実績' },
      { id: generateId(), type: 'checklist', content: '完了したタスク1', checked: true },
      { id: generateId(), type: 'checklist', content: '完了したタスク2', checked: true },
      { id: generateId(), type: 'checklist', content: '進行中のタスク', checked: false },
      { id: generateId(), type: 'h2', content: '課題・問題点' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '来週の計画' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h2', content: '所感・備考' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'manual',
    name: 'マニュアル・手順書',
    icon: 'bookOpen',
    description: '操作手順・業務マニュアル',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: '操作マニュアル' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: '概要' },
      { id: generateId(), type: 'paragraph', content: 'このマニュアルの目的と対象を記載します。' },
      { id: generateId(), type: 'h1', content: '事前準備' },
      { id: generateId(), type: 'callout', content: '必要なもの・前提条件をここに記載', data: { variant: 'info' } },
      { id: generateId(), type: 'h1', content: '手順' },
      { id: generateId(), type: 'h2', content: 'ステップ1' },
      { id: generateId(), type: 'numbered', content: '操作内容を記載' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h2', content: 'ステップ2' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h1', content: 'トラブルシューティング' },
      { id: generateId(), type: 'callout', content: 'よくある問題と対処法', data: { variant: 'warning' } },
      { id: generateId(), type: 'h1', content: '問い合わせ先' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'contract',
    name: '契約書',
    icon: 'shield',
    description: '基本契約書テンプレート',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '○○契約書', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '甲（以下「甲」という）と乙（以下「乙」という）は、以下のとおり契約を締結する。' },
      { id: generateId(), type: 'h2', content: '第1条（目的）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第2条（契約期間）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第3条（対価）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第4条（秘密保持）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第5条（解約）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第6条（協議事項）' },
      { id: generateId(), type: 'paragraph', content: '本契約に定めのない事項については、甲乙協議の上解決する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '以上の合意を証するため、本契約書2通を作成し、甲乙記名押印の上、各1通を保有する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '甲: 　　　　　　　　　印' },
      { id: generateId(), type: 'paragraph', content: '乙: 　　　　　　　　　印' },
    ],
  },
  {
    id: 'press-release',
    name: 'プレスリリース',
    icon: 'megaphone',
    description: '報道発表・ニュースリリース',
    buildDoc: () => [
      { id: generateId(), type: 'paragraph', content: '報道関係者各位', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '株式会社〇〇', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '【タイトル】○○に関するお知らせ', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: 'リード文: ニュースの要約を1〜2文で記載します。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '背景' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '詳細' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '今後の展開' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'paragraph', content: '【本件に関するお問い合わせ先】' },
      { id: generateId(), type: 'paragraph', content: '株式会社〇〇 広報部\nTEL: \nEmail: ' },
    ],
  },
  {
    id: 'faq',
    name: 'FAQ・Q&A',
    icon: 'helpCircle',
    description: 'よくある質問集',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: 'よくあるご質問（FAQ）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'カテゴリ1' },
      { id: generateId(), type: 'h3', content: 'Q1. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
      { id: generateId(), type: 'h3', content: 'Q2. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
      { id: generateId(), type: 'h2', content: 'カテゴリ2' },
      { id: generateId(), type: 'h3', content: 'Q3. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
    ],
  },
  {
    id: 'onboarding',
    name: 'オンボーディング資料',
    icon: 'rocket',
    description: '新入社員向けガイド',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: 'オンボーディングガイド' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: 'ようこそ！' },
      { id: generateId(), type: 'callout', content: 'このガイドは新しく参加されたメンバーのためのものです。', data: { variant: 'info' } },
      { id: generateId(), type: 'h2', content: '会社概要' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '組織構成' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '初日にやること' },
      { id: generateId(), type: 'checklist', content: 'アカウント設定', checked: false },
      { id: generateId(), type: 'checklist', content: '開発環境のセットアップ', checked: false },
      { id: generateId(), type: 'checklist', content: 'Slack/Teamsへの参加', checked: false },
      { id: generateId(), type: 'checklist', content: 'チームメンバーへの挨拶', checked: false },
      { id: generateId(), type: 'h1', content: '最初の1週間' },
      { id: generateId(), type: 'numbered', content: 'コードベースの理解' },
      { id: generateId(), type: 'numbered', content: '開発フローの確認' },
      { id: generateId(), type: 'numbered', content: '最初のタスクに着手' },
      { id: generateId(), type: 'h1', content: 'よくある質問' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '連絡先' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
]
