export * from './document-store'
export {
  listDocuments as cloudListDocuments,
  createDocument as cloudCreateDocument,
  getDocument,
  getSlideDoc as cloudGetSlideDoc,
  getDocDoc as cloudGetDocDoc,
  getSpreadsheetDoc as cloudGetSpreadsheetDoc,
  saveDocument,
  saveSlideDoc as cloudSaveSlideDoc,
  saveDocDoc as cloudSaveDocDoc,
  saveSpreadsheetDoc as cloudSaveSpreadsheetDoc,
  deleteDocument as cloudDeleteDocument,
  duplicateDocument as cloudDuplicateDocument,
  getFavorites,
  toggleFavorite,
  purgeExpiredTrash,
  isInTrash,
  getTrashIds,
  getTrashTimeRemaining,
  getTrashDeletedAt,
  moveToTrash,
  restoreFromTrash,
  permanentlyDelete,
  getFolders,
  saveFolders,
  getFolderMap,
  setDocFolder,
  searchDocumentContent,
  getAllTags,
  saveAllTags,
  getDocTags,
  setDocTags,
  getAllDocTags,
  getDocumentList,
  generateAPIResponse,
  getDocumentLink,
} from './cloud-store'
export * from './offline-store'
