import type { Block } from '@/types'
import { generateId } from '../utils'

export interface DocTemplate {
  id: string
  name: string
  icon: string
  description: string
  buildDoc: () => Block[]
}

export const DOC_TEMPLATES: DocTemplate[] = [
  {
    id: 'blank',
    name: '空白ドキュメント',
    icon: 'file',
    description: '白紙から始める',
    buildDoc: () => [{ id: generateId(), type: 'paragraph', content: '' }],
  },
  {
    id: 'business-letter',
    name: 'ビジネスレター',
    icon: 'mail',
    description: 'ビジネス文書・送付状',
    buildDoc: () => [
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '差出人名\n所属・部署\n住所\n電話番号\nメールアドレス' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '宛先名 様\n所属・部署\n住所' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '拝啓　時下ますますご清祥のこととお慶び申し上げます。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '本文をここに入力してください。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '何卒よろしくお願い申し上げます。' },
      { id: generateId(), type: 'paragraph', content: '敬具' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '署名\n役職\n氏名', align: 'right' },
    ],
  },
  {
    id: 'meeting',
    name: '議事録',
    icon: 'notebookPen',
    description: '会議の記録・決定事項',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '会議議事録' },
      { id: generateId(), type: 'paragraph', content: '日時: 20XX年XX月XX日 XX:XX〜XX:XX' },
      { id: generateId(), type: 'paragraph', content: '参加者: ' },
      { id: generateId(), type: 'h2', content: '議題1' },
      { id: generateId(), type: 'bullet', content: '議論内容を記載' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '議題2' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: 'アクションアイテム' },
      { id: generateId(), type: 'checklist', content: '担当者: タスク内容（期限: XX月XX日）', checked: false },
      { id: generateId(), type: 'checklist', content: '', checked: false },
      { id: generateId(), type: 'h2', content: '次回予定' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'proposal',
    name: 'プロジェクト企画書',
    icon: 'clipboardList',
    description: '企画・提案の構成テンプレート',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: 'プロジェクト企画書' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: '概要' },
      { id: generateId(), type: 'paragraph', content: 'プロジェクトの全体像を簡潔に記載します。' },
      { id: generateId(), type: 'h2', content: '背景' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '目的' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'スコープ' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'タイムライン' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '予算' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'report',
    name: 'レポート',
    icon: 'barChart',
    description: '学術・業務レポート',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: 'レポートタイトル' },
      { id: generateId(), type: 'h2', content: '要旨' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'はじめに' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '方法' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '結果' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '結論' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'resume',
    name: '履歴書',
    icon: 'user',
    description: '職務経歴・自己紹介',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '履歴書' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'h2', content: '基本情報' },
      { id: generateId(), type: 'paragraph', content: '氏名: ' },
      { id: generateId(), type: 'paragraph', content: '生年月日: ' },
      { id: generateId(), type: 'paragraph', content: '住所: ' },
      { id: generateId(), type: 'paragraph', content: '連絡先: ' },
      { id: generateId(), type: 'h2', content: '学歴' },
      { id: generateId(), type: 'paragraph', content: '20XX年X月　〇〇大学 〇〇学部 卒業' },
      { id: generateId(), type: 'h2', content: '職歴' },
      { id: generateId(), type: 'paragraph', content: '20XX年X月　株式会社〇〇 入社' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '資格・スキル' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '自己PR' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'weekly-report',
    name: '週次報告書',
    icon: 'calendar',
    description: '週の業務報告・進捗管理',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '週次報告書' },
      { id: generateId(), type: 'paragraph', content: '報告者: 　　　　報告日: 20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '対象期間: XX月XX日〜XX月XX日' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'h2', content: '今週の実績' },
      { id: generateId(), type: 'checklist', content: '完了したタスク1', checked: true },
      { id: generateId(), type: 'checklist', content: '完了したタスク2', checked: true },
      { id: generateId(), type: 'checklist', content: '進行中のタスク', checked: false },
      { id: generateId(), type: 'h2', content: '課題・問題点' },
      { id: generateId(), type: 'bullet', content: '' },
      { id: generateId(), type: 'h2', content: '来週の計画' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h2', content: '所感・備考' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'manual',
    name: 'マニュアル・手順書',
    icon: 'bookOpen',
    description: '操作手順・業務マニュアル',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: '操作マニュアル' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: '概要' },
      { id: generateId(), type: 'paragraph', content: 'このマニュアルの目的と対象を記載します。' },
      { id: generateId(), type: 'h1', content: '事前準備' },
      { id: generateId(), type: 'callout', content: '必要なもの・前提条件をここに記載', data: { variant: 'info' } },
      { id: generateId(), type: 'h1', content: '手順' },
      { id: generateId(), type: 'h2', content: 'ステップ1' },
      { id: generateId(), type: 'numbered', content: '操作内容を記載' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h2', content: 'ステップ2' },
      { id: generateId(), type: 'numbered', content: '' },
      { id: generateId(), type: 'h1', content: 'トラブルシューティング' },
      { id: generateId(), type: 'callout', content: 'よくある問題と対処法', data: { variant: 'warning' } },
      { id: generateId(), type: 'h1', content: '問い合わせ先' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'contract',
    name: '契約書',
    icon: 'shield',
    description: '基本契約書テンプレート',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '○○契約書', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '甲（以下「甲」という）と乙（以下「乙」という）は、以下のとおり契約を締結する。' },
      { id: generateId(), type: 'h2', content: '第1条（目的）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第2条（契約期間）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第3条（対価）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第4条（秘密保持）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第5条（解約）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第6条（協議事項）' },
      { id: generateId(), type: 'paragraph', content: '本契約に定めのない事項については、甲乙協議の上解決する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '以上の合意を証するため、本契約書2通を作成し、甲乙記名押印の上、各1通を保有する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '甲: 　　　　　　　　　印' },
      { id: generateId(), type: 'paragraph', content: '乙: 　　　　　　　　　印' },
    ],
  },
  {
    id: 'press-release',
    name: 'プレスリリース',
    icon: 'megaphone',
    description: '報道発表・ニュースリリース',
    buildDoc: () => [
      { id: generateId(), type: 'paragraph', content: '報道関係者各位', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '株式会社〇〇', align: 'right' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '【タイトル】○○に関するお知らせ', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: 'リード文: ニュースの要約を1〜2文で記載します。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '背景' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '詳細' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '今後の展開' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'paragraph', content: '【本件に関するお問い合わせ先】' },
      { id: generateId(), type: 'paragraph', content: '株式会社〇〇 広報部\nTEL: \nEmail: ' },
    ],
  },
  {
    id: 'faq',
    name: 'FAQ・Q&A',
    icon: 'helpCircle',
    description: 'よくある質問集',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: 'よくあるご質問（FAQ）' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: 'カテゴリ1' },
      { id: generateId(), type: 'h3', content: 'Q1. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
      { id: generateId(), type: 'h3', content: 'Q2. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
      { id: generateId(), type: 'h2', content: 'カテゴリ2' },
      { id: generateId(), type: 'h3', content: 'Q3. 質問内容を記載してください' },
      { id: generateId(), type: 'quote', content: 'A. 回答内容を記載してください。' },
    ],
  },
  {
    id: 'onboarding',
    name: 'オンボーディング資料',
    icon: 'rocket',
    description: '新入社員向けガイド',
    buildDoc: () => [
      { id: generateId(), type: 'cover-page', content: 'オンボーディングガイド' },
      { id: generateId(), type: 'toc', content: '' },
      { id: generateId(), type: 'h1', content: 'ようこそ！' },
      { id: generateId(), type: 'callout', content: 'このガイドは新しく参加されたメンバーのためのものです。', data: { variant: 'info' } },
      { id: generateId(), type: 'h2', content: '会社概要' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '組織構成' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '初日にやること' },
      { id: generateId(), type: 'checklist', content: 'アカウント設定', checked: false },
      { id: generateId(), type: 'checklist', content: '開発環境のセットアップ', checked: false },
      { id: generateId(), type: 'checklist', content: 'Slack/Teamsへの参加', checked: false },
      { id: generateId(), type: 'checklist', content: 'チームメンバーへの挨拶', checked: false },
      { id: generateId(), type: 'h1', content: '最初の1週間' },
      { id: generateId(), type: 'numbered', content: 'コードベースの理解' },
      { id: generateId(), type: 'numbered', content: '開発フローの確認' },
      { id: generateId(), type: 'numbered', content: '最初のタスクに着手' },
      { id: generateId(), type: 'h1', content: 'よくある質問' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h1', content: '連絡先' },
      { id: generateId(), type: 'paragraph', content: '' },
    ],
  },
  {
    id: 'meeting-minutes',
    name: '議事録（詳細版）',
    icon: 'notebookPen',
    description: 'スタートアップ向け詳細議事録',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '議事録', align: 'center' },
      { id: generateId(), type: 'divider', content: '' },
      { id: generateId(), type: 'h2', content: '会議名' },
      { id: generateId(), type: 'paragraph', content: '（会議名を入力）' },
      { id: generateId(), type: 'h2', content: '日時' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日（X） XX:XX〜XX:XX' },
      { id: generateId(), type: 'h2', content: '参加者' },
      { id: generateId(), type: 'bullet', content: '氏名（役職）' },
      { id: generateId(), type: 'bullet', content: '氏名（役職）' },
      { id: generateId(), type: 'bullet', content: '氏名（役職）' },
      { id: generateId(), type: 'h2', content: 'アジェンダ' },
      { id: generateId(), type: 'numbered', content: '議題1' },
      { id: generateId(), type: 'numbered', content: '議題2' },
      { id: generateId(), type: 'numbered', content: '議題3' },
      { id: generateId(), type: 'h2', content: '議事内容' },
      { id: generateId(), type: 'h3', content: '議題1: （タイトル）' },
      { id: generateId(), type: 'paragraph', content: '議論の要点を記載してください。' },
      { id: generateId(), type: 'h3', content: '議題2: （タイトル）' },
      { id: generateId(), type: 'paragraph', content: '議論の要点を記載してください。' },
      { id: generateId(), type: 'h3', content: '議題3: （タイトル）' },
      { id: generateId(), type: 'paragraph', content: '議論の要点を記載してください。' },
      { id: generateId(), type: 'h2', content: 'アクションアイテム' },
      { id: generateId(), type: 'checklist', content: '担当者: タスク内容（期限: XX月XX日）', checked: false },
      { id: generateId(), type: 'checklist', content: '担当者: タスク内容（期限: XX月XX日）', checked: false },
      { id: generateId(), type: 'checklist', content: '担当者: タスク内容（期限: XX月XX日）', checked: false },
      { id: generateId(), type: 'h2', content: '次回予定' },
      { id: generateId(), type: 'paragraph', content: '日時: 20XX年XX月XX日（X） XX:XX〜\n場所: \n議題: ' },
    ],
  },
  {
    id: 'nda',
    name: 'NDA（秘密保持契約書）',
    icon: 'shield',
    description: '秘密保持契約書テンプレート',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '秘密保持契約書', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '株式会社○○（以下「甲」という）と株式会社△△（以下「乙」という）は、相互の秘密情報の取扱いについて、以下のとおり秘密保持契約（以下「本契約」という）を締結する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第1条（目的）' },
      { id: generateId(), type: 'paragraph', content: '本契約は、甲乙間で○○に関する検討・協議（以下「本目的」という）を行うにあたり、相互に開示する秘密情報の取扱いを定めることを目的とする。' },
      { id: generateId(), type: 'h2', content: '第2条（秘密情報の定義）' },
      { id: generateId(), type: 'paragraph', content: '本契約において「秘密情報」とは、本目的に関連して、一方の当事者（以下「開示者」という）が他方の当事者（以下「受領者」という）に対し、書面、口頭、電磁的方法その他の手段により開示した一切の情報をいう。ただし、以下の情報は秘密情報に含まないものとする。' },
      { id: generateId(), type: 'bullet', content: '開示を受けた時点で既に公知であった情報' },
      { id: generateId(), type: 'bullet', content: '開示を受けた後、受領者の責によらず公知となった情報' },
      { id: generateId(), type: 'bullet', content: '開示を受ける前から受領者が適法に保有していた情報' },
      { id: generateId(), type: 'bullet', content: '正当な権限を有する第三者から秘密保持義務を負うことなく取得した情報' },
      { id: generateId(), type: 'bullet', content: '秘密情報によらず独自に開発した情報' },
      { id: generateId(), type: 'h2', content: '第3条（秘密保持義務）' },
      { id: generateId(), type: 'paragraph', content: '受領者は、秘密情報を本目的以外の目的で使用してはならず、開示者の書面による事前の承諾なく第三者に開示又は漏洩してはならない。' },
      { id: generateId(), type: 'h2', content: '第4条（秘密情報の管理）' },
      { id: generateId(), type: 'paragraph', content: '受領者は、秘密情報を善良なる管理者の注意をもって管理し、秘密情報への不正アクセス、紛失、破壊、改ざん及び漏洩等の防止のために必要な措置を講じるものとする。' },
      { id: generateId(), type: 'h2', content: '第5条（秘密情報の返還・破棄）' },
      { id: generateId(), type: 'paragraph', content: '受領者は、開示者から要求があった場合又は本契約が終了した場合、秘密情報及びその複製物を速やかに返還又は破棄するものとする。' },
      { id: generateId(), type: 'h2', content: '第6条（有効期間）' },
      { id: generateId(), type: 'paragraph', content: '本契約の有効期間は、本契約締結日から○年間とする。ただし、本契約終了後も、第3条及び第4条の規定は、なお○年間効力を有するものとする。' },
      { id: generateId(), type: 'h2', content: '第7条（損害賠償）' },
      { id: generateId(), type: 'paragraph', content: '甲又は乙は、本契約に違反して相手方に損害を与えた場合、その損害を賠償する責任を負う。' },
      { id: generateId(), type: 'h2', content: '第8条（協議事項）' },
      { id: generateId(), type: 'paragraph', content: '本契約に定めのない事項又は本契約の解釈に疑義が生じた場合は、甲乙誠意をもって協議の上解決する。' },
      { id: generateId(), type: 'h2', content: '第9条（管轄裁判所）' },
      { id: generateId(), type: 'paragraph', content: '本契約に関する一切の紛争は、○○地方裁判所を第一審の専属的合意管轄裁判所とする。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '以上の合意を証するため、本契約書2通を作成し、甲乙記名押印の上、各1通を保有する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '甲: 株式会社○○\n代表取締役　　　　　　　　　印' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '乙: 株式会社△△\n代表取締役　　　　　　　　　印' },
    ],
  },
  {
    id: 'outsourcing-contract',
    name: '業務委託契約書',
    icon: 'shield',
    description: '業務委託に関する基本契約書',
    buildDoc: () => [
      { id: generateId(), type: 'h1', content: '業務委託契約書', align: 'center' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '株式会社○○（以下「甲」という）と○○○○（以下「乙」という）は、業務の委託に関し、以下のとおり契約（以下「本契約」という）を締結する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'h2', content: '第1条（委託業務の内容）' },
      { id: generateId(), type: 'paragraph', content: '甲は乙に対し、以下の業務（以下「本業務」という）を委託し、乙はこれを受託する。' },
      { id: generateId(), type: 'bullet', content: '業務内容1: ' },
      { id: generateId(), type: 'bullet', content: '業務内容2: ' },
      { id: generateId(), type: 'bullet', content: '成果物: ' },
      { id: generateId(), type: 'h2', content: '第2条（契約期間）' },
      { id: generateId(), type: 'paragraph', content: '本契約の有効期間は、20XX年XX月XX日から20XX年XX月XX日までとする。' },
      { id: generateId(), type: 'h2', content: '第3条（委託料及び支払方法）' },
      { id: generateId(), type: 'paragraph', content: '1. 甲は乙に対し、本業務の対価として金○○円（税別）を支払う。\n2. 支払方法: 毎月末日締め、翌月末日払いとする。\n3. 振込手数料は甲の負担とする。' },
      { id: generateId(), type: 'h2', content: '第4条（再委託の禁止）' },
      { id: generateId(), type: 'paragraph', content: '乙は、甲の書面による事前の承諾なく、本業務の全部又は一部を第三者に再委託してはならない。' },
      { id: generateId(), type: 'h2', content: '第5条（秘密保持）' },
      { id: generateId(), type: 'paragraph', content: '甲及び乙は、本契約に関連して知り得た相手方の秘密情報を、相手方の書面による事前の承諾なく第三者に開示又は漏洩してはならない。本条の規定は、本契約終了後も○年間効力を有する。' },
      { id: generateId(), type: 'h2', content: '第6条（知的財産権）' },
      { id: generateId(), type: 'paragraph', content: '本業務により生じた成果物に関する著作権その他の知的財産権は、委託料の完済をもって甲に帰属するものとする。' },
      { id: generateId(), type: 'h2', content: '第7条（契約不適合責任）' },
      { id: generateId(), type: 'paragraph', content: '成果物に契約不適合が発見された場合、乙は甲の通知後○日以内に無償で修正を行うものとする。ただし、納品後○ヶ月を経過した場合はこの限りでない。' },
      { id: generateId(), type: 'h2', content: '第8条（解約）' },
      { id: generateId(), type: 'paragraph', content: '1. 甲又は乙は、○ヶ月前までに書面により通知することで本契約を解約できる。\n2. 相手方が本契約に違反した場合、催告の上是正されないときは、直ちに本契約を解除できる。' },
      { id: generateId(), type: 'h2', content: '第9条（損害賠償）' },
      { id: generateId(), type: 'paragraph', content: '甲又は乙は、本契約に違反して相手方に損害を与えた場合、その損害を賠償する責任を負う。' },
      { id: generateId(), type: 'h2', content: '第10条（反社会的勢力の排除）' },
      { id: generateId(), type: 'paragraph', content: '甲及び乙は、自らが反社会的勢力に該当しないことを表明し保証する。' },
      { id: generateId(), type: 'h2', content: '第11条（協議事項）' },
      { id: generateId(), type: 'paragraph', content: '本契約に定めのない事項又は本契約の解釈に疑義が生じた場合は、甲乙誠意をもって協議の上解決する。' },
      { id: generateId(), type: 'h2', content: '第12条（管轄裁判所）' },
      { id: generateId(), type: 'paragraph', content: '本契約に関する一切の紛争は、○○地方裁判所を第一審の専属的合意管轄裁判所とする。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '以上の合意を証するため、本契約書2通を作成し、甲乙記名押印の上、各1通を保有する。' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '20XX年XX月XX日' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '甲: 株式会社○○\n代表取締役　　　　　　　　　印' },
      { id: generateId(), type: 'paragraph', content: '' },
      { id: generateId(), type: 'paragraph', content: '乙: ○○○○\n住所: \n氏名: 　　　　　　　　　　　印' },
    ],
  },
]
