import type { Slide, SlideTextElement } from '@/types'
import { generateId } from '../utils'

export interface SlideTemplate {
  id: string
  name: string
  description: string
  buildSlide: (themeKey?: string) => Slide
  /** Multi-slide templates return an array of slides */
  buildSlides?: (themeKey?: string) => Slide[]
}

function el(overrides: Partial<SlideTextElement>): SlideTextElement {
  return {
    id: generateId(),
    type: 'title',
    content: '',
    x: 10,
    y: 40,
    w: 80,
    h: 15,
    fontSize: 48,
    fontWeight: '700',
    align: 'center',
    ...overrides,
  }
}

export const SLIDE_TEMPLATES: SlideTemplate[] = [
  {
    id: 'blank',
    name: 'ブランク',
    description: 'タイトルのみ',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [el({ content: 'タイトルを入力', x: 10, y: 38, w: 80, fontSize: 56, align: 'center' })],
    }),
  },
  {
    id: 'title-content',
    name: 'タイトル + コンテンツ',
    description: 'タイトルと本文',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'タイトル', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
        el({
          content: 'ここに本文を入力してください。内容を簡潔にまとめて記載します。',
          x: 8,
          y: 34,
          w: 84,
          fontSize: 22,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'section-break',
    name: 'セクション区切り',
    description: '大きな中央タイトル',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'セクション 1', x: 10, y: 30, w: 80, fontSize: 64, align: 'center', type: 'title' }),
        el({
          content: 'サブタイトルまたは説明',
          x: 20,
          y: 56,
          w: 60,
          fontSize: 20,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
  },
  {
    id: 'bullets',
    name: 'キーポイント',
    description: 'タイトル + 箇条書き',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'キーポイント', x: 8, y: 10, w: 84, fontSize: 40, align: 'left', type: 'title' }),
        el({
          content:
            '• ポイント 1 をここに入力\n• ポイント 2 をここに入力\n• ポイント 3 をここに入力\n• ポイント 4 をここに入力',
          x: 8,
          y: 30,
          w: 84,
          fontSize: 22,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'two-column',
    name: '2カラム',
    description: '左右2列レイアウト',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'タイトル', x: 8, y: 8, w: 84, fontSize: 38, align: 'left', type: 'title' }),
        el({
          content: '左側の内容\nここに説明を記載',
          x: 8,
          y: 30,
          w: 40,
          fontSize: 20,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
        el({
          content: '右側の内容\nここに説明を記載',
          x: 52,
          y: 30,
          w: 40,
          fontSize: 20,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'closing',
    name: 'クロージング',
    description: 'ありがとう / 締めスライド',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({
          content: 'ご清聴ありがとうございました',
          x: 10,
          y: 33,
          w: 80,
          fontSize: 48,
          align: 'center',
          type: 'title',
        }),
        el({
          content: 'お問い合わせ先を入力',
          x: 20,
          y: 60,
          w: 60,
          fontSize: 18,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
  },
  {
    id: 'quote',
    name: '引用',
    description: '大きな引用テキスト',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({
          content: '"ここに印象的な引用を入力"',
          x: 10,
          y: 25,
          w: 80,
          fontSize: 36,
          fontWeight: '300',
          align: 'center',
          type: 'body',
        }),
        el({
          content: '— 引用元',
          x: 20,
          y: 62,
          w: 60,
          fontSize: 18,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
  },
  {
    id: 'stats',
    name: '数値ハイライト',
    description: '3つの主要指標',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: '主要指標', x: 8, y: 8, w: 84, fontSize: 36, align: 'center', type: 'title' }),
        el({
          content: '150%\n成長率',
          x: 5,
          y: 35,
          w: 28,
          fontSize: 28,
          fontWeight: '700',
          align: 'center',
          type: 'body',
        }),
        el({
          content: '10,000+\nユーザー数',
          x: 36,
          y: 35,
          w: 28,
          fontSize: 28,
          fontWeight: '700',
          align: 'center',
          type: 'body',
        }),
        el({
          content: '99.9%\n稼働率',
          x: 67,
          y: 35,
          w: 28,
          fontSize: 28,
          fontWeight: '700',
          align: 'center',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'timeline',
    name: 'タイムライン',
    description: 'ステップ・時系列',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'ロードマップ', x: 8, y: 8, w: 84, fontSize: 36, align: 'left', type: 'title' }),
        el({
          content: 'Phase 1 — 調査・企画\nPhase 2 — 設計・開発\nPhase 3 — テスト・検証\nPhase 4 — リリース・運用',
          x: 8,
          y: 30,
          w: 84,
          fontSize: 22,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'comparison',
    name: '比較',
    description: 'Before/After・A vs B',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: '比較', x: 8, y: 8, w: 84, fontSize: 36, align: 'center', type: 'title' }),
        el({
          content: 'Before\n• 課題 1\n• 課題 2\n• 課題 3',
          x: 5,
          y: 28,
          w: 42,
          fontSize: 20,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
        el({
          content: 'After\n• 改善 1\n• 改善 2\n• 改善 3',
          x: 53,
          y: 28,
          w: 42,
          fontSize: 20,
          fontWeight: '400',
          align: 'left',
          type: 'body',
        }),
      ],
    }),
  },
  {
    id: 'pitch-deck',
    name: '投資家向けピッチデック',
    description: '投資家向けピッチプレゼン（9枚構成）',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: '会社名', x: 10, y: 30, w: 80, fontSize: 64, align: 'center', type: 'title' }),
        el({
          content: 'One-liner: 一言で何をしているか',
          x: 20,
          y: 56,
          w: 60,
          fontSize: 20,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
    buildSlides: (themeKey = 'dark-blue') => [
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '会社名', x: 10, y: 30, w: 80, fontSize: 64, align: 'center', type: 'title' }),
          el({
            content: 'キャッチコピー・タグラインを入力',
            x: 20,
            y: 56,
            w: 60,
            fontSize: 20,
            fontWeight: '400',
            align: 'center',
            type: 'subtitle',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '課題', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: 'ターゲットが抱える具体的なペインポイント\n• 課題1: 現状の問題点\n• 課題2: 既存ソリューションの不足\n• 課題3: 市場が見過ごしている痛み',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '解決策', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '私たちのプロダクトがどう解決するか\n\n• 提供価値1\n• 提供価値2\n• 競合との差別化ポイント',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '市場規模', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: 'TAM（総市場規模）: ¥○○億\nSAM（対象市場規模）: ¥○○億\nSOM（獲得可能市場規模）: ¥○○億',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'プロダクト', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '主要機能・特徴\n• 機能1: 説明\n• 機能2: 説明\n• 機能3: 説明\n\n※スクリーンショットやデモ動画をここに配置',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'トラクション', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: 'これまでの実績・成長指標\n• ユーザー数: \n• MRR: \n• 前月比成長率: \n• 主要マイルストーン: ',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'ビジネスモデル', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '収益化の仕組み\n• 料金体系: \n• 単価: \n• LTV: \n• 主要な収益源: ',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'チーム', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '創業メンバー・経営陣\n• CEO: 氏名 — 経歴\n• CTO: 氏名 — 経歴\n• COO: 氏名 — 経歴\n• アドバイザー: ',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '資金調達', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '調達希望額: ¥○○M\n\n資金用途:\n• プロダクト開発: ○○%\n• 営業・マーケティング: ○○%\n• 採用・組織: ○○%\n• 運転資金: ○○%',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
    ],
  },
  {
    id: 'monthly-report',
    name: '月次報告書',
    description: 'スタートアップの月次進捗報告（6枚構成）',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: '月次報告書', x: 10, y: 30, w: 80, fontSize: 64, align: 'center', type: 'title' }),
        el({
          content: '20XX年X月度',
          x: 20,
          y: 56,
          w: 60,
          fontSize: 20,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
    buildSlides: (themeKey = 'dark-blue') => [
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '月次報告書', x: 10, y: 30, w: 80, fontSize: 64, align: 'center', type: 'title' }),
          el({
            content: '20XX年X月度',
            x: 20,
            y: 56,
            w: 60,
            fontSize: 20,
            fontWeight: '400',
            align: 'center',
            type: 'subtitle',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'KPIサマリー', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: 'MRR: ¥XXX → ¥XXX（前月比 +XX%）\nARR: ¥X,XXX\nユーザー数: XXX → XXX\nチャーン率: X.X%\nNPS: XX',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '売上推移', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '月次売上の推移とトレンド\n\n4月: ¥XXX万\n5月: ¥XXX万\n6月: ¥XXX万\n\n前年同月比: +XX%',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '主要マイルストーン', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '今月達成したマイルストーン\n• 達成事項1\n• 達成事項2\n• 達成事項3',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '課題と対策', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '課題1: \n→ 対策: \n\n課題2: \n→ 対策: \n\n課題3: \n→ 対策: ',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '来月の計画', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '重点施策\n• 目標1: \n• 目標2: \n• 目標3: \n\n来月のKPI目標\n• MRR: ¥XXX\n• ユーザー数: XXX',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
    ],
  },
  {
    id: 'team-meeting',
    name: 'チームミーティング',
    description: '定例会議・全体会議',
    buildSlide: (themeKey = 'dark-blue') => ({
      id: generateId(),
      themeKey: themeKey as Slide['themeKey'],
      elements: [
        el({ content: 'チームミーティング', x: 10, y: 30, w: 80, fontSize: 56, align: 'center', type: 'title' }),
        el({
          content: '20XX年XX月XX日',
          x: 20,
          y: 56,
          w: 60,
          fontSize: 20,
          fontWeight: '400',
          align: 'center',
          type: 'subtitle',
        }),
      ],
    }),
    buildSlides: (themeKey = 'dark-blue') => [
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'チームミーティング', x: 10, y: 30, w: 80, fontSize: 56, align: 'center', type: 'title' }),
          el({
            content: '20XX年XX月XX日',
            x: 20,
            y: 56,
            w: 60,
            fontSize: 20,
            fontWeight: '400',
            align: 'center',
            type: 'subtitle',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'アジェンダ', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '1. 前回のアクションアイテム確認\n2. 各チームの進捗報告\n3. 今週の課題・相談\n4. 来週の予定\n5. その他',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: '進捗報告', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '開発チーム: \n営業チーム: \nマーケティング: ',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
      {
        id: generateId(),
        themeKey: themeKey as Slide['themeKey'],
        elements: [
          el({ content: 'アクションアイテム', x: 8, y: 12, w: 84, fontSize: 42, align: 'left', type: 'title' }),
          el({
            content: '• [ ] 担当: タスク (期限: )\n• [ ] 担当: タスク (期限: )\n• [ ] 担当: タスク (期限: )',
            x: 8,
            y: 34,
            w: 84,
            fontSize: 22,
            fontWeight: '400',
            align: 'left',
            type: 'body',
          }),
        ],
      },
    ],
  },
]
